apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    access: proxy
    editable: true

  - name: Loki
    type: loki
    url: http://loki:3100
    access: proxy
    editable: true

  - name: Tempo
    type: tempo
    url: http://tempo:3200 # Tempo의 HTTP 포트는 3200이지만, Grafana-Tempo 통합은 3100 포트를 사용
    access: proxy
    editable: true
    isDefault: false
    version: 1
    # Prometheus와 Loki 데이터 소스를 연동
    # 이를 통해 Grafana에서 트레이스를 보고 관련 메트릭과 로그를 바로 확인할 수 있다
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus # 서비스 맵을 위해 Prometheus 데이터 소스 UID를 저장
      tracesToLogs:
        datasourceUid: loki # 트레이스에서 로그로 이동하기 위해 Loki 데이터 소스 UID를 저장
        tags: [ 'job', 'application', 'level' ] #로그에 필터링할 태그를 지정
        mappedTags: ['namespace'] # 트레이스 태그와 로그 태그의 매핑
        spanStartTimeShift: '1m'
        spanEndTimeShift: '1m'
        lokiSearch: true